In [ ]:
import pandas as pd

In [ ]:
diabetes=pd.read_csv('/content/Dataset of Diabetes .csv')
d_copy=diabetes.copy()

In [ ]:
diabetes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   ID         1000 non-null   int64
 1   No_Pation  1000 non-null   int64
 2   Gender     1000 non-null   object
 3   AGE        1000 non-null   int64
 4   Urea       1000 non-null   float64
 5   Cr         1000 non-null   int64
 6   HbA1c      1000 non-null   float64
 7   Chol       1000 non-null   float64
 8   TG         1000 non-null   float64
 9   HDL        1000 non-null   float64
 10  LDL        1000 non-null   float64
 11  VLDL       1000 non-null   float64
 12  BMI        1000 non-null   float64
 13  CLASS      1000 non-null   object
dtypes: float64(8), int64(4), object(2)
memory usage: 109.5+ KB

In [ ]:
diabetes.describe()

,ID,No_Pation,AGE,Urea,Cr,HbA1c,Chol,TG,HDL,LDL,VLDL,BMI
count,1000.000000,1.000000e+03,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,340.500000,2.705514e+05,53.528000,5.124743,68.943000,8.281160,4.862820,2.349610,1.204750,2.609790,1.854700,29.578020
std,240.397673,3.380758e+06,8.799241,2.935165,59.984747,2.534003,1.301738,1.401176,0.660414,1.115102,3.663599,4.962388
min,1.000000,1.230000e+02,20.000000,0.500000,6.000000,0.900000,0.000000,0.300000,0.200000,0.300000,0.100000,19.000000
25%,125.750000,2.406375e+04,51.000000,3.700000,48.000000,6.500000,4.000000,1.500000,0.900000,1.800000,0.700000,26.000000
50%,300.500000,3.439550e+04,55.000000,4.600000,60.000000,8.000000,4.800000,2.000000,1.100000,2.500000,0.900000,30.000000
75%,550.250000,4.538425e+04,59.000000,5.700000,73.000000,10.200000,5.600000,2.900000,1.300000,3.300000,1.500000,33.000000
max,800.000000,7.543566e+07,79.000000,38.900000,800.000000,16.000000,10.300000,13.800000,9.900000,9.900000,35.000000,47.750000

In [ ]:
adult=pd.read_csv('/content/adult.csv')

In [ ]:
adult.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48842 entries, 0 to 48841
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   age              48842 non-null  int64
 1   workclass        48842 non-null  object
 2   fnlwgt           48842 non-null  int64
 3   education        48842 non-null  object
 4   educational-num  48842 non-null  int64
 5   marital-status   48842 non-null  object
 6   occupation       48842 non-null  object
 7   relationship     48842 non-null  object
 8   race             48842 non-null  object
 9   gender           48842 non-null  object
 10  capital-gain     48842 non-null  int64
 11  capital-loss     48842 non-null  int64
 12  hours-per-week   48842 non-null  int64
 13  native-country   48842 non-null  object
 14  income           48842 non-null  object
dtypes: int64(6), object(9)
memory usage: 5.6+ MB

In [ ]:
adult.describe()

,age,fnlwgt,educational-num,capital-gain,capital-loss,hours-per-week
count,48842.000000,4.884200e+04,48842.000000,48842.000000,48842.000000,48842.000000
mean,38.643585,1.896641e+05,10.078089,1079.067626,87.502314,40.422382
std,13.710510,1.056040e+05,2.570973,7452.019058,403.004552,12.391444
min,17.000000,1.228500e+04,1.000000,0.000000,0.000000,1.000000
25%,28.000000,1.175505e+05,9.000000,0.000000,0.000000,40.000000
50%,37.000000,1.781445e+05,10.000000,0.000000,0.000000,40.000000
75%,48.000000,2.376420e+05,12.000000,0.000000,0.000000,45.000000
max,90.000000,1.490400e+06,16.000000,99999.000000,4356.000000,99.000000

In [ ]:
d_miss=diabetes.isnull().sum()
print(d_miss)
print(d_miss[d_miss > 0])

ID           0
No_Pation    0
Gender       0
AGE          0
Urea         0
Cr           0
HbA1c        0
Chol         0
TG           0
HDL          0
LDL          0
VLDL         0
BMI          0
CLASS        0
dtype: int64
Series([], dtype: int64)

In [ ]:
a_miss=adult.isnull().sum()
print(a_miss)
print(a_miss[a_miss > 0])

age                0
workclass          0
fnlwgt             0
education          0
educational-num    0
marital-status     0
occupation         0
relationship       0
race               0
gender             0
capital-gain       0
capital-loss       0
hours-per-week     0
native-country     0
income             0
dtype: int64
Series([], dtype: int64)

In [ ]:
#Handling categorical variables
from sklearn.preprocessing import OrdinalEncoder, OneHotEncoder

In [ ]:
#Gender and class are categorical as they are of object datatype
print(diabetes["Gender"].value_counts())
print(diabetes["CLASS"].value_counts())

Gender
M    565
F    434
f      1
Name: count, dtype: int64
CLASS
Y     840
N     102
P      53
Y       4
N       1
Name: count, dtype: int64

In [ ]:
diabetes["Gender"] = diabetes["Gender"].replace("f", "F")
updated_file_path = "/content/Dataset of Diabetes .csv"  # Replace with the desired path
diabetes.to_csv(updated_file_path, index=False)

In [ ]:
diabetes["Gender"].value_counts()

Gender
M    565
F    435
Name: count, dtype: int64

In [ ]:
ordinal_encoder = OrdinalEncoder(categories=[["M", "F"]])
diabetes["Gender_Encoded"] = ordinal_encoder.fit_transform(diabetes[["Gender"]])

In [ ]:
diabetes["CLASS"] = diabetes["CLASS"].replace(["N ","Y "],["N","Y"])
updated_file_path = "/content/Dataset of Diabetes .csv"  # Replace with the desired path
diabetes.to_csv(updated_file_path, index=False)

In [ ]:
diabetes['CLASS'].value_counts()

CLASS
Y    844
N    103
P     53
Name: count, dtype: int64

In [ ]:
onehot_encoder = OneHotEncoder()
encoded_data = onehot_encoder.fit_transform(diabetes[["CLASS"]])
encoded_array = encoded_data.toarray()
encoded_df = pd.DataFrame(encoded_array, columns=onehot_encoder.get_feature_names_out(["CLASS"]))
df_encoded = pd.concat([diabetes, encoded_df], axis=1)

df_encoded.drop("Gender", axis=1, inplace=True)
df_encoded.drop("CLASS", axis=1, inplace=True)

print(df_encoded. head())

    ID  No_Pation  AGE  Urea  Cr  HbA1c  Chol   TG  HDL  LDL  VLDL   BMI  \
0  502      17975   50   4.7  46    4.9   4.2  0.9  2.4  1.4   0.5  24.0
1  735      34221   26   4.5  62    4.9   3.7  1.4  1.1  2.1   0.6  23.0
2  420      47975   50   4.7  46    4.9   4.2  0.9  2.4  1.4   0.5  24.0
3  680      87656   50   4.7  46    4.9   4.2  0.9  2.4  1.4   0.5  24.0
4  504      34223   33   7.1  46    4.9   4.9  1.0  0.8  2.0   0.4  21.0

   Gender_Encoded  CLASS_N  CLASS_P  CLASS_Y
0             1.0      1.0      0.0      0.0
1             0.0      1.0      0.0      0.0
2             1.0      1.0      0.0      0.0
3             1.0      1.0      0.0      0.0
4             0.0      1.0      0.0      0.0

In [ ]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from scipy import stats

In [ ]:
normalizer = MinMaxScaler()
df_encoded[['No_Pation']] = normalizer.fit_transform(df_encoded[['No_Pation']])
df_encoded.head()

,ID,No_Pation,AGE,Urea,Cr,HbA1c,Chol,TG,HDL,LDL,VLDL,BMI,Gender_Encoded,CLASS_N,CLASS_P,CLASS_Y
0,502,0.000237,50,4.7,46,4.9,4.2,0.9,2.4,1.4,0.5,24.0,1.0,1.0,0.0,0.0
1,735,0.000452,26,4.5,62,4.9,3.7,1.4,1.1,2.1,0.6,23.0,0.0,1.0,0.0,0.0
2,420,0.000634,50,4.7,46,4.9,4.2,0.9,2.4,1.4,0.5,24.0,1.0,1.0,0.0,0.0
3,680,0.001160,50,4.7,46,4.9,4.2,0.9,2.4,1.4,0.5,24.0,1.0,1.0,0.0,0.0
4,504,0.000452,33,7.1,46,4.9,4.9,1.0,0.8,2.0,0.4,21.0,0.0,1.0,0.0,0.0

In [ ]:
scaler = StandardScaler()
df_encoded[['AGE']] = scaler.fit_transform(df_encoded[['AGE']])
df_encoded.head()

,ID,No_Pation,AGE,Urea,Cr,HbA1c,Chol,TG,HDL,LDL,VLDL,BMI,Gender_Encoded,CLASS_N,CLASS_P,CLASS_Y
0,502,0.000237,-0.401144,4.7,46,4.9,4.2,0.9,2.4,1.4,0.5,24.0,1.0,1.0,0.0,0.0
1,735,0.000452,-3.130017,4.5,62,4.9,3.7,1.4,1.1,2.1,0.6,23.0,0.0,1.0,0.0,0.0
2,420,0.000634,-0.401144,4.7,46,4.9,4.2,0.9,2.4,1.4,0.5,24.0,1.0,1.0,0.0,0.0
3,680,0.001160,-0.401144,4.7,46,4.9,4.2,0.9,2.4,1.4,0.5,24.0,1.0,1.0,0.0,0.0
4,504,0.000452,-2.334096,7.1,46,4.9,4.9,1.0,0.8,2.0,0.4,21.0,0.0,1.0,0.0,0.0

In [ ]:
import numpy as np

In [ ]:
df_encoded_copy1=df_encoded
df_encoded_copy2=df_encoded
df_encoded_copy3=df_encoded

Q1 = df_encoded_copy1['No_Pation'].quantile(0.25)
Q3 = df_encoded_copy1['No_Pation'].quantile(0.75)
IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR
df_encoded_copy1['No_Pation'] = np.where(df_encoded_copy1['No_Pation'] > upper_bound, upper_bound,
                        np.where(df_encoded_copy1['No_Pation'] < lower_bound, lower_bound, df_encoded_copy1['No_Pation']))

print(df_encoded_copy1.head())

    ID  No_Pation       AGE  Urea  Cr  HbA1c  Chol   TG  HDL  LDL  VLDL   BMI  \
0  502   0.000237 -0.401144   4.7  46    4.9   4.2  0.9  2.4  1.4   0.5  24.0
1  735   0.000452 -3.130017   4.5  62    4.9   3.7  1.4  1.1  2.1   0.6  23.0
2  420   0.000634 -0.401144   4.7  46    4.9   4.2  0.9  2.4  1.4   0.5  24.0
3  680   0.001024 -0.401144   4.7  46    4.9   4.2  0.9  2.4  1.4   0.5  24.0
4  504   0.000452 -2.334096   7.1  46    4.9   4.9  1.0  0.8  2.0   0.4  21.0

   Gender_Encoded  CLASS_N  CLASS_P  CLASS_Y
0             1.0      1.0      0.0      0.0
1             0.0      1.0      0.0      0.0
2             1.0      1.0      0.0      0.0
3             1.0      1.0      0.0      0.0
4             0.0      1.0      0.0      0.0

In [ ]:
df_encoded_copy2['No_Pation_zscore'] = stats.zscore(df_encoded_copy2['No_Pation'])
df_encoded_copy2['No_Pation'] = np.where(df_encoded_copy2['No_Pation_zscore'].abs() > 3, np.nan, df_encoded_copy2['No_Pation'])  # Replace outliers with NaN
print(df_encoded_copy2.head())

    ID  No_Pation       AGE  Urea  Cr  HbA1c  Chol   TG  HDL  LDL  VLDL   BMI  \
0  502   0.000237 -0.401144   4.7  46    4.9   4.2  0.9  2.4  1.4   0.5  24.0
1  735   0.000452 -3.130017   4.5  62    4.9   3.7  1.4  1.1  2.1   0.6  23.0
2  420   0.000634 -0.401144   4.7  46    4.9   4.2  0.9  2.4  1.4   0.5  24.0
3  680   0.001024 -0.401144   4.7  46    4.9   4.2  0.9  2.4  1.4   0.5  24.0
4  504   0.000452 -2.334096   7.1  46    4.9   4.9  1.0  0.8  2.0   0.4  21.0

   Gender_Encoded  CLASS_N  CLASS_P  CLASS_Y  No_Pation_zscore
0             1.0      1.0      0.0      0.0         -0.919118
1             0.0      1.0      0.0      0.0         -0.087690
2             1.0      1.0      0.0      0.0          0.616204
3             1.0      1.0      0.0      0.0          2.120307
4             0.0      1.0      0.0      0.0         -0.087588

In [ ]:
df_encoded_copy3['No_Pation_zscore'] = stats.zscore(df_encoded_copy3['No_Pation'])
median_salary = df_encoded_copy3['No_Pation'].median()
df_encoded_copy3['No_Pation'] = np.where(df_encoded_copy3['No_Pation_zscore'].abs() > 3, median_salary, df_encoded_copy3['No_Pation'])
print(df_encoded_copy3.head())

    ID  No_Pation       AGE  Urea  Cr  HbA1c  Chol   TG  HDL  LDL  VLDL   BMI  \
0  502   0.000237 -0.401144   4.7  46    4.9   4.2  0.9  2.4  1.4   0.5  24.0
1  735   0.000452 -3.130017   4.5  62    4.9   3.7  1.4  1.1  2.1   0.6  23.0
2  420   0.000634 -0.401144   4.7  46    4.9   4.2  0.9  2.4  1.4   0.5  24.0
3  680   0.001024 -0.401144   4.7  46    4.9   4.2  0.9  2.4  1.4   0.5  24.0
4  504   0.000452 -2.334096   7.1  46    4.9   4.9  1.0  0.8  2.0   0.4  21.0

   Gender_Encoded  CLASS_N  CLASS_P  CLASS_Y  No_Pation_zscore
0             1.0      1.0      0.0      0.0         -0.919118
1             0.0      1.0      0.0      0.0         -0.087690
2             1.0      1.0      0.0      0.0          0.616204
3             1.0      1.0      0.0      0.0          2.120307
4             0.0      1.0      0.0      0.0         -0.087588